// <auto-generated />
using System;
using COPI_API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace COPI_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250901130224_MigracaoUnidadeTipo")]
    partial class MigracaoUnidadeTipo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("COPI_API.Models.AdminEntities.Divisao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Divisoes");
                });

            modelBuilder.Entity("COPI_API.Models.AdminEntities.Servidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CargoOuFuncao")
                        .HasColumnType("longtext");

                    b.Property<string>("Celular")
                        .HasColumnType("longtext");

                    b.Property<string>("ChefiaImediata")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DivisaoId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HorarioEntrada")
                        .HasColumnType("longtext");

                    b.Property<string>("HorarioSaida")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PontoSei")
                        .HasColumnType("longtext");

                    b.Property<string>("RF")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UltimoAcesso")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DivisaoId");

                    b.ToTable("Servidores");
                });

            modelBuilder.Entity("COPI_API.Models.AdminEntities.Unidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeAbreviado")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("COPI_API.Models.MetaEntities.AcaoEstrategica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AcaoExecutada")
                        .HasColumnType("longtext");

                    b.Property<bool>("Batida")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Comentarios")
                        .HasColumnType("longtext");

                    b.Property<bool>("Concluido")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("DataCumprimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<bool>("DocumentoValidado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DocumentosAnalise")
                        .HasColumnType("longtext");

                    b.Property<string>("Evidencia")
                        .HasColumnType("longtext");

                    b.Property<int>("MetaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PrazoFinal")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Progresso")
                        .HasColumnType("int");

                    b.Property<string>("ResponsavelAprovacao")
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsavelExecucao")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MetaId");

                    b.ToTable("AcoesEstrategicas");
                });

            modelBuilder.Entity("COPI_API.Models.MetaEntities.Meta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataCumprimento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInic")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<int>("DivisaoId")
                        .HasColumnType("int");

                    b.Property<string>("OrigemMeta")
                        .HasColumnType("longtext");

                    b.Property<int>("Progresso")
                        .HasColumnType("int");

                    b.Property<string>("Setor")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Metas");
                });

            modelBuilder.Entity("COPI_API.Models.MetaEntities.Tarefa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AcaoEstrategicaId")
                        .HasColumnType("int");

                    b.Property<string>("AvaliacaoDoc")
                        .HasColumnType("longtext");

                    b.Property<bool>("Batida")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Comentario")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataCumprimento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PrazoFinal")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Progresso")
                        .HasColumnType("int");

                    b.Property<string>("Responsavel")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("StatusExecucao")
                        .HasColumnType("longtext");

                    b.Property<string>("Titulo")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AcaoEstrategicaId");

                    b.ToTable("Tarefas");
                });

            modelBuilder.Entity("COPI_API.Models.PIBPEntities.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("NivelGerenciadoAtingido")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("NivelIntegradoAtingido")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("NivelPadronizadoAtingido")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("NotaIMPIBP")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NotaNG")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NotaNI")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NotaNP")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("COPI_API.Models.PIBPEntities.Ciclo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("Encerrado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Ciclos");
                });

            modelBuilder.Entity("COPI_API.Models.PIBPEntities.Eixo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Eixos");
                });

            modelBuilder.Entity("COPI_API.Models.PIBPEntities.KPI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("EixoId")
                        .HasColumnType("int");

                    b.Property<int?>("NivelId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<double?>("Pontuacao")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("EixoId");

                    b.HasIndex("NivelId");

                    b.ToTable("KPIs");
                });

            modelBuilder.Entity("COPI_API.Models.PIBPEntities.Nivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Niveis");
                });

            modelBuilder.Entity("COPI_API.Models.PIBPEntities.ResultadoKPI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AvaliacaoEscrita")
                        .HasColumnType("longtext");

                    b.Property<int?>("AvaliacaoId")
                        .HasColumnType("int");

                    b.Property<int>("CicloId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KPIId")
                        .HasColumnType("int");

                    b.Property<string>("Prova")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<int>("UnidadeKPIId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AvaliacaoId");

                    b.HasIndex("CicloId");

                    b.HasIndex("KPIId");

                    b.HasIndex("UnidadeKPIId");

                    b.ToTable("ResultadosKPI");
                });

            modelBuilder.Entity("COPI_API.Models.PIBPEntities.StatusPIBP", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CicloId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UnidadeKPIId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CicloId");

                    b.HasIndex("UnidadeKPIId");

                    b.ToTable("StatusPIBP");
                });

            modelBuilder.Entity("COPI_API.Models.PIBPEntities.UnidadeKPI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("SEI")
                        .HasColumnType("longtext");

                    b.Property<int>("ServidorId")
                        .HasColumnType("int");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServidorId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("UnidadesKPI");
                });

            modelBuilder.Entity("COPI_API.Models.AdminEntities.Servidor", b =>
                {
                    b.HasOne("COPI_API.Models.AdminEntities.Divisao", "Divisao")
                        .WithMany("Servidores")
                        .HasForeignKey("DivisaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Divisao");
                });

            modelBuilder.Entity("COPI_API.Models.MetaEntities.AcaoEstrategica", b =>
                {
                    b.HasOne("COPI_API.Models.MetaEntities.Meta", "Meta")
                        .WithMany("AcoesEstrategicas")
                        .HasForeignKey("MetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meta");
                });

            modelBuilder.Entity("COPI_API.Models.MetaEntities.Tarefa", b =>
                {
                    b.HasOne("COPI_API.Models.MetaEntities.AcaoEstrategica", "AcaoEstrategica")
                        .WithMany("Tarefas")
                        .HasForeignKey("AcaoEstrategicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AcaoEstrategica");
                });

            modelBuilder.Entity("COPI_API.Models.PIBPEntities.KPI", b =>
                {
                    b.HasOne("COPI_API.Models.PIBPEntities.Eixo", "Eixo")
                        .WithMany()
                        .HasForeignKey("EixoId");

                    b.HasOne("COPI_API.Models.PIBPEntities.Nivel", "Nivel")
                        .WithMany()
                        .HasForeignKey("NivelId");

                    b.Navigation("Eixo");

                    b.Navigation("Nivel");
                });

            modelBuilder.Entity("COPI_API.Models.PIBPEntities.ResultadoKPI", b =>
                {
                    b.HasOne("COPI_API.Models.PIBPEntities.Avaliacao", null)
                        .WithMany("Resultados")
                        .HasForeignKey("AvaliacaoId");

                    b.HasOne("COPI_API.Models.PIBPEntities.Ciclo", "Ciclo")
                        .WithMany()
                        .HasForeignKey("CicloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("COPI_API.Models.PIBPEntities.KPI", "KPI")
                        .WithMany()
                        .HasForeignKey("KPIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("COPI_API.Models.PIBPEntities.UnidadeKPI", "UnidadeKPI")
                        .WithMany("Resultados")
                        .HasForeignKey("UnidadeKPIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciclo");

                    b.Navigation("KPI");

                    b.Navigation("UnidadeKPI");
                });

            modelBuilder.Entity("COPI_API.Models.PIBPEntities.StatusPIBP", b =>
                {
                    b.HasOne("COPI_API.Models.PIBPEntities.Ciclo", "Ciclo")
                        .WithMany()
                        .HasForeignKey("CicloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("COPI_API.Models.PIBPEntities.UnidadeKPI", "UnidadeKPI")
                        .WithMany()
                        .HasForeignKey("UnidadeKPIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciclo");

                    b.Navigation("UnidadeKPI");
                });

            modelBuilder.Entity("COPI_API.Models.PIBPEntities.UnidadeKPI", b =>
                {
                    b.HasOne("COPI_API.Models.AdminEntities.Servidor", "Servidor")
                        .WithMany("UnidadesKpiResponsaveis")
                        .HasForeignKey("ServidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("COPI_API.Models.AdminEntities.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servidor");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("COPI_API.Models.AdminEntities.Divisao", b =>
                {
                    b.Navigation("Servidores");
                });

            modelBuilder.Entity("COPI_API.Models.AdminEntities.Servidor", b =>
                {
                    b.Navigation("UnidadesKpiResponsaveis");
                });

            modelBuilder.Entity("COPI_API.Models.MetaEntities.AcaoEstrategica", b =>
                {
                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("COPI_API.Models.MetaEntities.Meta", b =>
                {
                    b.Navigation("AcoesEstrategicas");
                });

            modelBuilder.Entity("COPI_API.Models.PIBPEntities.Avaliacao", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("COPI_API.Models.PIBPEntities.UnidadeKPI", b =>
                {
                    b.Navigation("Resultados");
                });
#pragma warning restore 612, 618
        }
    }
}
