// <auto-generated />
using System;
using COPI_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace COPI_API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("COPI_API.Models.Avaliacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("NivelGerenciadoAtingido")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("NivelIntegradoAtingido")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("NivelPadronizadoAtingido")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("NotaIMPIBP")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NotaNG")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NotaNI")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("NotaNP")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Avaliacoes");
                });

            modelBuilder.Entity("COPI_API.Models.Ciclo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataFim")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<bool?>("Encerrado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Ciclos");
                });

            modelBuilder.Entity("COPI_API.Models.Divisao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Divisoes");
                });

            modelBuilder.Entity("COPI_API.Models.Eixo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Eixos");
                });

            modelBuilder.Entity("COPI_API.Models.Nivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Niveis");
                });

            modelBuilder.Entity("COPI_API.Models.ResultadoKPI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AvaliacaoEscrita")
                        .HasColumnType("longtext");

                    b.Property<int?>("AvaliacaoId")
                        .HasColumnType("int");

                    b.Property<int>("CicloId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KPIId")
                        .HasColumnType("int");

                    b.Property<string>("Prova")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<int>("UnidadeKPIId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AvaliacaoId");

                    b.HasIndex("CicloId");

                    b.HasIndex("KPIId");

                    b.HasIndex("UnidadeKPIId");

                    b.ToTable("ResultadosKPI");
                });

            modelBuilder.Entity("COPI_API.Models.Servidor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CargoOuFuncao")
                        .HasColumnType("longtext");

                    b.Property<string>("Celular")
                        .HasColumnType("longtext");

                    b.Property<string>("ChefiaImediata")
                        .HasColumnType("longtext");

                    b.Property<int>("DivisaoId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("HorarioEntrada")
                        .HasColumnType("longtext");

                    b.Property<string>("HorarioSaida")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("PontoSei")
                        .HasColumnType("longtext");

                    b.Property<string>("RF")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("DivisaoId");

                    b.ToTable("Servidores");
                });

            modelBuilder.Entity("COPI_API.Models.Unidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeAbreviado")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("COPI_API.Models.UnidadeKPI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("SEI")
                        .HasColumnType("longtext");

                    b.Property<int>("ServidorId")
                        .HasColumnType("int");

                    b.Property<int>("UnidadeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServidorId");

                    b.HasIndex("UnidadeId");

                    b.ToTable("UnidadesKPI");
                });

            modelBuilder.Entity("KPI", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("EixoId")
                        .HasColumnType("int");

                    b.Property<int?>("NivelId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<double?>("Pontuacao")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("EixoId");

                    b.HasIndex("NivelId");

                    b.ToTable("KPIs");
                });

            modelBuilder.Entity("COPI_API.Models.ResultadoKPI", b =>
                {
                    b.HasOne("COPI_API.Models.Avaliacao", null)
                        .WithMany("Resultados")
                        .HasForeignKey("AvaliacaoId");

                    b.HasOne("COPI_API.Models.Ciclo", "Ciclo")
                        .WithMany()
                        .HasForeignKey("CicloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KPI", "KPI")
                        .WithMany()
                        .HasForeignKey("KPIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("COPI_API.Models.UnidadeKPI", "UnidadeKPI")
                        .WithMany("Resultados")
                        .HasForeignKey("UnidadeKPIId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ciclo");

                    b.Navigation("KPI");

                    b.Navigation("UnidadeKPI");
                });

            modelBuilder.Entity("COPI_API.Models.Servidor", b =>
                {
                    b.HasOne("COPI_API.Models.Divisao", "Divisao")
                        .WithMany("Servidores")
                        .HasForeignKey("DivisaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Divisao");
                });

            modelBuilder.Entity("COPI_API.Models.UnidadeKPI", b =>
                {
                    b.HasOne("COPI_API.Models.Servidor", "Servidor")
                        .WithMany("UnidadesKpiResponsaveis")
                        .HasForeignKey("ServidorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("COPI_API.Models.Unidade", "Unidade")
                        .WithMany()
                        .HasForeignKey("UnidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Servidor");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("KPI", b =>
                {
                    b.HasOne("COPI_API.Models.Eixo", "Eixo")
                        .WithMany("KPIs")
                        .HasForeignKey("EixoId");

                    b.HasOne("COPI_API.Models.Nivel", "Nivel")
                        .WithMany("KPIs")
                        .HasForeignKey("NivelId");

                    b.Navigation("Eixo");

                    b.Navigation("Nivel");
                });

            modelBuilder.Entity("COPI_API.Models.Avaliacao", b =>
                {
                    b.Navigation("Resultados");
                });

            modelBuilder.Entity("COPI_API.Models.Divisao", b =>
                {
                    b.Navigation("Servidores");
                });

            modelBuilder.Entity("COPI_API.Models.Eixo", b =>
                {
                    b.Navigation("KPIs");
                });

            modelBuilder.Entity("COPI_API.Models.Nivel", b =>
                {
                    b.Navigation("KPIs");
                });

            modelBuilder.Entity("COPI_API.Models.Servidor", b =>
                {
                    b.Navigation("UnidadesKpiResponsaveis");
                });

            modelBuilder.Entity("COPI_API.Models.UnidadeKPI", b =>
                {
                    b.Navigation("Resultados");
                });
#pragma warning restore 612, 618
        }
    }
}
